FROM timpark/ubuntu
MAINTAINER Tim Park <tpark@microsoft.com>

RUN apt-get install -y python-software-properties --fix-missing
RUN add-apt-repository ppa:chris-lea/node.js
RUN apt-get update
RUN apt-get install -y nodejs
