#!/bin/bash

azure vm create \
coreos-1 \
coreos-test \
ops \
--affinity-group n2-affinity \
--vm-size small \
--vm-name n2-api-1 \
--ssh 22001 \
--ssh-cert /Users/timpark/dev/nitrogen/ops/keys/nitrogen-vm-auth.pem \
--no-ssh-password \
--virtual-network-name n2-network \
--subnet-names VMs \
--custom-data coreos-1.yml
