#!/bin/bash

azure vm create \
coreos-1 \
coreos-test \
ops \
--vm-size small \
--vm-name coreos-1 \
--ssh 22 \
--ssh-cert ../../keys/ssh-cert.pem \
--no-ssh-password \
--virtual-network-name coreos-network \
--custom-data coreos-1.yml

azure vm create \
coreos-2 \
coreos-test \
ops \
--vm-size small \
--vm-name coreos-2 \
--ssh 22 \
--ssh-cert ../../keys/ssh-cert.pem \
--no-ssh-password \
--virtual-network-name coreos-network \
--custom-data coreos-2.yml

